# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:
  - job: Parameter
    pool:
      vmImage: ubuntu-latest
    variables:
      currentDate: $(Get-Date -Format 'yyyy-MM-dd HH:00:00')
    steps:
      - task: CreateWorkItem@2
        inputs:
          workItemType: 'Task'
          title: 'New Build $(Build.BuildNumber) $(Build.DefinitionName)'
          assignedTo: 'IT Admin <admin@uatsandbox.onmicrosoft.com>'
          associate: true
          authType: 'internal'
      - powershell: echo "##vso[task.setvariable variable=startDate;isOutput=true]$(currentDate)"
        name: setParameter
  - job: ChangeRequest
    dependsOn:
      - Parameter
    condition: succeeded()
    pool:
      name: Server
    variables:
      startDate: $[ dependencies.Parameter.outputs['setParameter.startDate'] ]
    steps:
      - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        inputs:
          connectedServiceName: 'dev201230-ARMS-ServiceNow DevOps Service Connection'
          applicationName: 'ARMS'
          changeRequestDetails: |
            {
              "autoCloseChange": true,
              "attributes": {
                "requested_by": {
                  "name": "DevOps Integration User"
                },
                "assignment_group": {
                  "name": "ARMS Support"
                },
                "chg_model": {
                  "name": "DevOps"
                },
                "category": "Service",
                "devops_change": true,
                "business_service": {
                  "name": "ARMS"
                },
                "service_offering": {
                  "name": "Offering"
                },
                "type": "Normal",
                "priority": "2",
                "short_description": "ARMS - New Build - $(Build.BuildNumber)",
                "comments": "This is a sample pipeline script to be added in your change step",
                "work_notes": "New Build $(Build.BuildNumber)",
                "start_date": "$(startDate)"
              }
            }