# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

stages:
- stage: ServiceNowDev
  displayName: 
  jobs:
    - job: nodeDev
      displayName: 'Install Node.js'
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'

    - job: ServiceNowChangeRecord
      dependsOn:
      - nodeDev
      condition: succeeded()
      pool:
        name: Server
      steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'dev201230-js-e2e-express-server-ServiceNow DevOps Service Connection'

