# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:
  - job: CreateWorkItem
    pool:
      vmImage: ubuntu-latest
    variables:
      areaPath: 'ARMS'
      iterationPath: 'ARMS\Sprint 1'
    steps:
      - task: CreateWorkItem@2
        inputs:
          workItemType: 'Product Backlog Item'
          title: 'New Build - $(Build.BuildNumber)'
          assignedTo: 'IT Admin <admin@uatsandbox.onmicrosoft.com>'
          areaPath: $(areaPath)
          iterationPath: $(iterationPath)
          fieldMappings: |
            Description=Hello World!
            Acceptance Criteria=Needs further details from @<itsupport@uatsandbox.onmicrosoft.com>
            Effort=1
            Business Value=10
          associate: true
          createOutputs: true
          outputVariables: |
            'parentID=ID'
          authType: 'internal'
      - script: echo $(parentID)
      