# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:
  - job: CreateParameter
    pool:
      vmImage: ubuntu-latest
    variables:
      startTime: $(Get-Date).ToString('yyyy-MM-dd HH:00:00')
      endTime: $(Get-Date).AddHours(1).ToString('yyyy-MM-dd HH:00:00')
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            echo "##vso[task.setvariable variable=startDate;isOutput=true]$(startTime)"
            echo "##vso[task.setvariable variable=endDate;isOutput=true]$(endTime)"
          pwsh: true
        name: setParameter
  - job: CreateChangeRequest
    dependsOn:
      - CreateParameter
    condition: succeeded()
    pool:
      name: Server
    variables:
      startDate: $[ dependencies.CreateParameter.outputs['setParameter.startDate'] ]
      endDate: $[ dependencies.CreateParameter.outputs['setParameter.endDate'] ]
    steps:
      - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        inputs:
          connectedServiceName: 'dev201230-ARMS-ServiceNow DevOps Service Connection'
          applicationName: 'ARMS'
          changeRequestDetails: |
            {
              "autoCloseChange": true,
              "attributes": {
                "requested_by": {
                  "name": "DevOps Integration User"
                },
                "assignment_group": {
                  "name": "ARMS Support"
                },
                "chg_model": {
                  "name": "DevOps"
                },
                "category": "Service",
                "devops_change": true,
                "business_service": {
                  "name": "ARMS"
                },
                "service_offering": {
                  "name": "Offering"
                },
                "type": "Normal",
                "priority": "2",
                "short_description": "ARMS - New Build - $(Build.BuildNumber)",
                "comments": "This is a sample pipeline script to be added in your change step",
                "work_notes": "New Build $(Build.BuildNumber)",
                "start_date": "$(startDate)",
                "end_date": "$(endDate)"
              }
            }
  - job: CreateWorkItem
    dependsOn:
      - CreateParameter
      - CreateChangeRequest
    condition: succeeded()
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: CreateWorkItem@2
        inputs:
          workItemType: 'Product Backlog Item'
          title: 'New Build - $(Build.BuildNumber)'
          assignedTo: 'IT Admin <admin@uatsandbox.onmicrosoft.com>'
          areaPath: 'ARMS'
          iterationPath: 'ARMS\Sprint 1'
          fieldMappings: |
            Description=Hello World!
            Acceptance Criteria=Needs further details from @<itsupport@uatsandbox.onmicrosoft.com>
            Effort=1
            Business Value=10
          associate: true
          authType: 'internal'
      