# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

stages:
- stage: ServiceNowDev
  displayName: 
  jobs:
    - job: ServiceNowChangeRecord
      displayName: 'Change Approval'
      pool:
        name: Server
      steps:
        - task: ServiceNow-DevOps-Server-Change-Acceleration@1
          inputs:
            connectedServiceName: 'dev201230-js-e2e-express-server-ServiceNow DevOps Service Connection'
            changeRequestDetails: |
              {
                "autoCloseChange": true,
                "attributes": {
                  "requested_by": {
                    "name": "IT Support"
                  },
                  "assignment_group": {
                    "name": "Change Management"
                  },
                  "chg_model": {
                    "name": "DevOps"
                  },
                  "category": "Service",
                  "devops_change": true,
                  "business_service": {
                    "name": "ARMS"
                  },
                  "service_offering": {
                    "name": "Offering"
                  },
                  "cmdb_ci": {
                    "name": "ARMS"
                  },
                  "priority": "2",
                  "comments": "This is a sample pipeline script to be added in your change step",
                  "work_notes": "Update this to work_notes",
                  "start_date": "2024-09-07 11:00:00",
                  "end_date": "2024-09-09 11:15:00"
                }
              }
    
    - job: nodeDev
      displayName: 'Install Node.js'
      dependsOn:
      - ServiceNowChangeRecord
      condition: succeeded()
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'


