# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

jobs:
  - job: CreateWorkItem
    condition: succeeded()
    pool:
      vmImage: ubuntu-latest
    variables:
      areaPath: 'ARMS'
      iterationPath: 'ARMS\Sprint 1'
    steps:
      - task: CreateWorkItem@2
        inputs:
          workItemType: 'Product Backlog Item'
          title: 'New Release - $(Build.BuildNumber)'
          assignedTo: 'IT Admin <admin@uatsandbox.onmicrosoft.com>'
          areaPath: $(areaPath)
          iterationPath: $(iterationPath)
          fieldMappings: |
            Description=Hello World!
            Acceptance Criteria=Needs further details from @<itsupport@uatsandbox.onmicrosoft.com>
            Effort=1
            Business Value=10
          associate: true
          createOutputs: true
          outputVariables: |
            parentID=ID
          authType: 'internal'
      - task: CreateWorkItem@2
        inputs:
          workItemType: 'Task'
          title: 'Implementation - $(Build.BuildNumber)'
          areaPath: $(areaPath)
          iterationPath: $(iterationPath)
          fieldMappings: |
            Tags=Implementation
          linkWorkItems: true
          linkType: 'System.LinkTypes.Hierarchy-Reverse'
          linkTarget: 'id'
          targetId: $(parentID)
          limitWorkItemLinksToSameProject: true
          authType: 'internal'
      - task: CreateWorkItem@2
        inputs:
          workItemType: 'Test Case'
          title: 'Testing - $(Build.BuildNumber)'
          areaPath: $(areaPath)
          iterationPath: $(iterationPath)
          fieldMappings: |
            Tags=Testing
            Automation status=Planned
          linkWorkItems: true
          linkType: 'Microsoft.VSTS.Common.TestedBy-Reverse'
          linkTarget: 'id'
          targetId: $(parentID)
          limitWorkItemLinksToSameProject: true
          createOutputs: true
          outputVariables: |
            childID=ID
          authType: 'internal'